import { Resend } from 'resend';
import { PublicError, escapeHtml, safeHeaderValue } from './http';
import type { StoredResume } from './storage';

type Fields = Record<string, string>;

function recipients(variable: string): string[] {
  const list = (process.env[variable] || '').split(',').map(value => value.trim()).filter(Boolean);
  if (!list.length) throw new PublicError('Notification recipients are not configured.', 503);
  return list;
}

function resend(): Resend {
  if (!process.env.RESEND_API_KEY) throw new PublicError('Email notifications are not configured.', 503);
  return new Resend(process.env.RESEND_API_KEY);
}

function rows(fields: Fields): string {
  return Object.entries(fields)
    .filter(([key]) => !['dataConsent', 'accuracyConfirmation', 'website', 'cf-turnstile-response'].includes(key))
    .map(([key, value]) => `<tr><th align="left" style="padding:8px;border-bottom:1px solid #ddd">${escapeHtml(key)}</th><td style="padding:8px;border-bottom:1px solid #ddd;white-space:pre-wrap">${escapeHtml(value)}</td></tr>`)
    .join('');
}

function plain(fields: Fields): string {
  return Object.entries(fields)
    .filter(([key]) => !['dataConsent', 'accuracyConfirmation', 'website', 'cf-turnstile-response'].includes(key))
    .map(([key, value]) => `${key}: ${value}`).join('\n');
}

async function send(to: string[], subject: string, heading: string, fields: Fields, extraHtml = '', extraText = ''): Promise<void> {
  const from = process.env.RESEND_FROM_EMAIL?.trim();
  if (!from) throw new PublicError('The notification sender is not configured.', 503);
  const replyTo = process.env.RESEND_REPLY_TO_EMAIL?.trim() || undefined;
  const result = await resend().emails.send({
    from,
    to,
    replyTo,
    subject: safeHeaderValue(subject, 180),
    html: `<div style="font-family:Arial,sans-serif;max-width:760px;margin:auto"><h1 style="color:#0b3a2b">${escapeHtml(heading)}</h1><p>This message was generated by Shane Perez’s personal professional website.</p><table style="border-collapse:collapse;width:100%">${rows(fields)}</table>${extraHtml}<p style="color:#555">Handle this information only through the approved privacy, recruitment, and retention process.</p></div>`,
    text: `${heading}\n\n${plain(fields)}\n${extraText}\n\nHandle this information only through the approved privacy, recruitment, and retention process.`
  });
  if (result.error) throw new PublicError('The notification could not be delivered.', 503);
}

export async function sendRecruitment(fields: Fields, resume: StoredResume): Promise<void> {
  const expiryHours = Math.max(1, Math.round(resume.expiresInSeconds / 3600));
  await send(
    recipients('RECRUITMENT_NOTIFICATION_EMAILS'),
    `New recruitment application — ${safeHeaderValue(fields.fullName)}`,
    'New recruitment application',
    fields,
    `<h2>Protected résumé</h2><p>Original file: ${escapeHtml(resume.originalName)}</p><p><a href="${escapeHtml(resume.signedUrl)}">Open the protected résumé</a> (expires in approximately ${expiryHours} hours).</p><p>This is a bearer link. Do not forward it to unauthorized recipients.</p>`,
    `\nProtected résumé: ${resume.signedUrl}\nLink expires in approximately ${expiryHours} hours. This is a bearer link; do not forward it.`
  );
}

export async function sendConsultation(fields: Fields): Promise<void> {
  await send(
    recipients('CONSULTATION_NOTIFICATION_EMAILS'),
    `New consultation request — ${safeHeaderValue(fields.fullName)}`,
    'New consultation request',
    fields,
    '<p><strong>The requested dates are preferences and are not automatically confirmed.</strong></p>'
  );
}

export async function sendContact(fields: Fields): Promise<void> {
  await send(
    recipients('CONTACT_NOTIFICATION_EMAILS'),
    `Website inquiry — ${safeHeaderValue(fields.subject)}`,
    'New website inquiry',
    fields
  );
}
